version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      #MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      #MARIADB_DB: imdb
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: toto
      #MARIADB_DATABASE: digicheese
      #MARIADB_PASSWORD: toto
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3310:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      #test: ["CMD", "root", "ping", "-h", "localhost"]
      start_period: 80s
      interval: 10s
      timeout: 60s
      retries: 5
    

  imdb:
    image: openjdk:17-jdk-slim
    build:
       context: .
       dockerfile: Dockerfile
    container_name: imdb
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    
    depends_on:
      mariadb:
        condition: service_healthy


volumes:
  mariadb_data: